"""corretion in rating feild in reviews1

Revision ID: 7aeeecc2fbdc
Revises: e2655781293b
Create Date: 2025-12-25 14:49:14.266146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7aeeecc2fbdc'
down_revision: Union[str, Sequence[str], None] = 'e2655781293b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
