"""added assoication table booktag table

Revision ID: dbd946a7568e
Revises: aa3b4a56b39c
Create Date: 2025-09-08 12:02:35.456886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbd946a7568e'
down_revision: Union[str, Sequence[str], None] = 'aa3b4a56b39c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booktag',
    sa.Column('book_id', sa.CHAR(length=36), nullable=False),
    sa.Column('tag_id', sa.CHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.uid'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.uid'], ),
    sa.PrimaryKeyConstraint('book_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booktag')
    # ### end Alembic commands ###
